---
title: "Filipinos in Manitoba"
output: 
  html_document:
    css: style.css
---

Winnipeg is the oldest significant Canadian settlement area west of southern Ontario. Since its founding, it has served as the primary population centre for Manitoba, which became the first western province to join confederation, in 1870, at which time its population was primarily of Indigenous (including Cree, Ojibway, and Métis), French, and Scottish ancestry. Historically, immigration to Canada, including Manitoba, has primarily been of (Western) European origin. Through the early and middle parts of the 20th century, Central and Eastern European countries increasingly contributed to the growing Canadian population, widening the ethnic diversity of the country while largely maintaining its ‘white’ racial character (see e.g. the discussion of the 1923 Chinese Exclusion Act in Canada 2005). In 1967, Canada adopted the Federal Skilled Worker Program (FSWP), which changed the racial make-up of immigrants significantly. The system shifted from previous policy privileging racial (i.e. white) background, towards a labour market-oriented immigration policy, with a ‘points’ system, focusing on demographic characteristics and accumulated human capital. This shift saw a new demographic of immigrants move to Canada, namely skilled workers from non-white source countries. 

Filipino migration to Canada can be broken down into three periods. In Winnipeg during the first period (1967-1974), the implementation of the FSWP triggered an initial wave of 300 nurses from the Philippines in 1967. This wave paved the way for a more important influx of Filipino skilled workers under the FSWP. After World War II, Winnipeg had become an important textile manufacturer, supplying all of the Prairie provinces. This led to approximately 1200 textile workers from the Philippines being employed in Winnipeg by 1972. These incoming nurses and textile workers meant that the majority of the first-period Filipino immigrants were young, professional-class females. Filipino immigrants to Winnipeg have continued to trend towards the educated, professional class. 
The second period (1974-1985) saw reduced immigration to Canada generally, somewhat counterbalanced by an increase in family-class immigration. Buoyed by these forces, Filipino immigration shifted from predominantly female to an increasing number of male immigrants during this period, reflecting general trends, as first-period immigrants brought family members to join them in Canada. During the third (contemporary) period, Filipino immigrants broadened their range of occupations, although female-specific service positions (e.g. domestic worker) dominated in Canada as a whole. With regards to Manitoba, however, the latter types of occupations have never been as predominant as in larger cities such as Toronto or Vancouver. This is reflected in the fact that the sex ratio for Filipino immigrants is far less biased towards females than males in Manitoba as compared with the national average.

More recently, many Filipino immigrants have taken advantage of the popular Manitoba Provincial Nominee Program, akin to the FSWP but at the provincial, rather than federal level. Manitoba was the first Canadian province to introduce such a provincial nominee program, which allows skilled workers to come to the province, and, importantly, bring their family over via Family Class, and settle permanently in the province. Following the second period of Filipino migration, The Philippines has consistently ranked as by far the top source country for immigrants to Manitoba, accounting for a minimum of 23% of all immigration into the province during the 1980s and 1990s, and rising to approximately 36% or more than one-third of all immigrants during the most recent decade surveyed, from 2006–2016. Tagalog, the official language of the Phillipines, is presently the most common non-official home language spoken among the immigrant population, at 58,910 speakers, nearly three times the number of speakers of second-ranked Punjabi at 20,400 speakers. 
